### ISSUE TITLE
Add a new Analysis-Button

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#12]
## Value proposition

As an User
I want a button on the Start-Page
So that I can create a new Analysis

## Description

![Image](https://user-images.githubusercontent.com/119793693/251762122-e08468b2-247e-49aa-b5bd-7736d0a69726.png)

## Acceptance criteria

- [x] Have a button on the start page
- [x] give it an icon
- [x] let it say "new analysis"/"Neue Analyse"
- [x] let it redirect the user to the "New Analysis"-Form

**Comment by sebastianwel** [comment]
LGTM - good scope and easy to understand 😁
