### ISSUE TITLE
New Analysis-Page

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#13]
## Value proposition

As an User
I want a page
So that I can choose, which kind of analysis I want to create

## Description

New-Analysis Page
![image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/b4552349-b80d-42b9-a94e-2af62dda2098)

Button on Start-Page to get to New Analysis
![image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/02bb59e2-8e60-42ec-91fe-31cd3a306f34)

## Acceptance criteria

- [x] have a `new page` for the new analysis
- [x] with a `back-button`, that takes me back to the start-page
- [x] have a` input field` for title
- [x] have a `input field` for date
- [x] ask the User which kind of analysis he wants to take
- [x] let there be `radio buttons `for the user to choose between the three types
- [x] have the `start page` link to the new page

**Comment by CarstenJahnke** [comment]
Hi Veliko, your value proposition is not complete - a copy-paste failure? 😄
Maybe try it this way:
As a user
I want a page where I can edit and select one of the different analyses
So that I can edit my data for a new analytics

Have you thought about a submit button as well? Or how do you save the form?

**Comment by vaupunkt** [comment]
hey @CarstenJahnke,
thank you for you input - i can see that my User Story could be misunderstood. The "real" form to create a analysis is the next step, here. i just want the user to choose between the three types 😊
I changed the user story to be more understandable!

**Comment by rueveydaakuel** [comment]
LGTM 👍
