### ISSUE TITLE
add the Kieslerkreis

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#39]
## Value proposition

As an User
I want a Kieslerkreis-Diagram
So that I can see, where I would position myself on it, when writing a new analysis

## Description

![Image](https://user-images.githubusercontent.com/119793693/254818852-7eddb1b4-f08e-4964-b6bf-b103b0fc8bee.png)

Detail: 
![Image](https://user-images.githubusercontent.com/119793693/254819524-336be8b0-2be6-4d50-a1f5-05ac01800dbb.png)

## Acceptance criteria

- [x] use a chart-rendering library like [`chart.js`](https://www.chartjs.org/) or [`recharts`](http://recharts.org/)
- [x] position it on the `new analysis form`, under the QuestionHeading for `Behaviour` / "Verhalten"
- [x] under the `description` render a `circle/spider-diagramm`
- [x] have the axis be labeled with "Dominant/offen"(top), "Freundlich/nähe" (right), "Unterwürfig/verschlossen" (bottom), "Feindselig, Distanz" (left)

--> functionality will be part of another user story

**Comment by StrongCurrent** [comment]
Actually looks quite good to me. According to my understanding you have confused the acceptance criteria with the tasks and the acceptance criteria is completely missing. please look at it again and change it accordingly.
