### ISSUE TITLE
add hover/onClick on Kieslerkreis-Diagramm

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#40]
## Value proposition

As an User
I want to click on different parts of the kieslerkreis
So that I can define my position in the situationanalysis

## Description

![Image](https://user-images.githubusercontent.com/119793693/254821556-980537d4-71fc-4821-9b82-0a6d6f6e6185.png)

![Image](https://user-images.githubusercontent.com/119793693/254821607-26325b73-7e67-4d22-993f-44c1c87341ff.png)

## Acceptance criteria

- [x] have a area under the kieslerkreis where the value of the selected area is rendered
- [x] have a hover and/or onClick behaviour for the different circle-sections
- [x] have the description/value to be rendered after selecting the section

**Comment by oliverhees** [comment]
Looks for good. But the tasks are completely missing here. Please change it accordingly.

**Comment by oliverhees** [comment]
Hi,

I just talked to our coach regarding the missing tasks and it seems to be ok. 

It is therefore ok and I have changed the status accordingly. 

Good job and sorry for the misunderstanding
