### ISSUE TITLE
edit the kieslerkreis-position in entries

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#42]
## Value proposition

As an User
I want to edit my position on the kieslerkreis in older entries
So that I can change it if i made a mistake

## Description

![Image](https://user-images.githubusercontent.com/119793693/254833477-1c9c9a5d-7eb4-401b-bc31-8363857771a3.png)

## Acceptance criteria

- [x] after click on the `edit button` - go into `editMode`
- [x] add the `kieslerkreis-component` from the `addAnalysis component `to change the position on the `diagram`
- [x] save the new position after editing to the `entries-array`

**Comment by FlorianNova** [comment]
Looks good to me! :)
