### ISSUE TITLE
add Kieslerkreis OverviewPage

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#46]
## Value proposition

As an User
I want to have a page with all my Kieslerkreis-Results
So that I can see my behavior, my wanted behavior and more information about the kieslerkreis

## Description

![Image](https://user-images.githubusercontent.com/119793693/255314866-cdfab01d-66a9-4a0a-9584-86ecaeb359d0.png)

![Image](https://user-images.githubusercontent.com/119793693/255314904-37dba038-7d7e-4b67-85c7-8c5e9744db48.png)

![Image](https://user-images.githubusercontent.com/119793693/255314970-eefc2311-4168-4efd-963a-522e24730a80.png)

## Acceptance criteria

- [ ] have a `new page` where i see the kieslerkreis
- [ ] have the results from the entries mapped on the kieslerkreis
- [ ] take the results from `behaviorKieslerkreis` and `behaviorChangedKieslerkreis`
- [ ] have a `description` about the kieslerkreis to the bottom

**Comment by ekat-br** [comment]
Understandable and clear user story!
