### ISSUE TITLE
create ConversationalForm

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#48]
## Value proposition

As an user
I want a chatbot to ask me questions
So that I can fill out the form more natural

## Description
![image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/fe53567c-778e-4a17-9f1f-e617a6d26703)
## Acceptance criteria

- [x] use [ConversationalForm](https://space10-community.github.io/conversational-form/docs/1.0.0/getting-started/) or something similar
- [x] rework all form-questions to chatbot questions
- [x] save the answered questions in the end as a new entry

**Comment by Roland-Hufnagel** [comment]
LGTM
