### ISSUE TITLE
add Readme-File

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#51]
## Value proposition

As an Developer
I want to a have a Readme-File on GitHub
So that I can see, what the app is about

## Acceptance criteria

- [x] Rewrite the existing Readme-File
- [x] Explain the used packages
- [x] Explain what you can do in the app
- [x] Explain CBASP-Therapie
- [x] explain the different analysis-types
- [x] explain the Kieslerkreis

**Comment by MonaHer** [comment]
LGTM :) Only one small typo in the second line of you value proposition: I want **to** have a Readme-File on GitHub
