### ISSUE TITLE
mySymptomsPage

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#52]
## Value proposition

As an User
I want a Page where I can see an overview for the different sections of symptoms
So that later add and read about my symptoms

## Description
![image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/45ff4174-de34-4cef-9a43-60408b957519)
## Acceptance criteria

- [x] have a page that shows the `4 different types of symptoms`. they will lead in the next step to filtered views of the entered symptoms

**Comment by Kheirah** [comment]
The story is good!

The only thing I'd recommend is to either **not include** the two buttons (_see all_ and _add_) or to **fully implement** their functionality. The way to think about it is this: You don't want to build something that doesn't work. The solution is to either not build it or fully build it.
