### ISSUE TITLE
Profilpage

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#62]
## Value proposition

As an User
I want a Profilpage
So that I can find links to my entries and other features

## Description

![Image](https://user-images.githubusercontent.com/119793693/256983732-797386c0-b5b6-4797-88c1-50824ab28403.png)

## Acceptance criteria

- [x] I want to see links to other options
- [x] I want to be able to click on "my analysis"
- [x] i want to be able to click on "my symptoms"
- [x] i want to be able to click on "kieslerkreis"
- [x] i want them to link to the corresponding page
- [x]  I want a `button` to go back to the Main/Homepage

**Comment by ekat-br** [comment]
Well, you're already through with the story. Anyway, looks good to me :)
